#!/usr/bin/node
console.log('C is fun');
console.log('Python is cool');
console.log('Javascript is amazing');
#!/usr/bin/node
if (process.argv.length <= 2) {
  console.log('No argument');
} else if (process.argv.length === 3) {
  console.log('Argument found');
} else if (process.argv.length > 3) {
  console.log('Arguments found');
}
